[package]
name = "nugen"
version = "0.1.0"
edition = "2021"
about="Nuspec CLI tool for awesome people"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
